name: recflow-web
exclude: ["CNAME", "README.md"]

gem:
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:

languages: ["en", "tw"]
exclude_from_localizations : ["css", "fonts", "img", "js", "favicon.png"]
